Port to 1.20.5/1.20.6
NucleoidMC/stimuli pull request #49
Opened 2024-04-30 23:12 UTC by Awakened-Redstone

A 1.20.5/1.20.6 port

No events were changed, only one parameter was deprecated due to the bow changes
The deprecation was used over removing for backwards compatibility

2024-04-30 23:29 UTC, Awakened-Redstone commented on src/main/java/xyz/nucleoid/stimuli/mixin/block/FlowerPotBlockMixin.java
I will look into it tomorrow, I MC is refusing to with x-forward

2024-04-30 23:29 UTC, Awakened-Redstone commented on src/main/java/xyz/nucleoid/stimuli/mixin/projectile/RangedWeaponItemMixin.java
> +              .onFireArrow(player, tool, item, -1, persistentProjectile);
I'm not sure, not that deep into mixins to know if they allow that, I'll see on the mixin help channel

2024-05-01 01:28 UTC, Awakened-Redstone commented on src/main/java/xyz/nucleoid/stimuli/mixin/projectile/RangedWeaponItemMixin.java
> +              .onFireArrow(player, tool, item, -1, persistentProjectile);
Seems possible, I'll work on it tomorrow since I can't test today

2024-05-01 16:16 UTC, Awakened-Redstone commented on src/main/java/xyz/nucleoid/stimuli/mixin/block/FlowerPotBlockMixin.java
It worked with no issues

2024-05-10 22:40 UTC, Awakened-Redstone commented
this comment is a bit late, but the flower pot and bow worked with no issues, I would like to try automating the tests more, but not really possible as most depend on player interaction

2024-05-12 10:40 UTC, Patbox requested changes

2024-05-12 10:40 UTC, Patbox commented on src/main/java/xyz/nucleoid/stimuli/mixin/projectile/RangedWeaponItemMixin.java
> +      locals = LocalCapture.CAPTURE_FAILHARD,
LocalCapture shouldn't be used anymore, switch to @Local from MixinExtras
https://github.com/LlamaLad7/MixinExtras/wiki/Local

2024-05-16 19:53 UTC, Awakened-Redstone commented
Did some more checking and added missing stuff, like the shearing event for the bogged
The wind charges should be covered by the explosion event

2024-05-18 11:32 UTC, merged